apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: birds-database
spec:
  memory: 800Mi
  cpu: "0.8"
  pgConfig:
    dbname: birds-database
    username: pgadmin
    appUser: admin
  highAvailability:
    enabled: false
