apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: birds
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/name: birds
    app.kubernetes.io/part-of: micropets-app
    micropets/kind: backend
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  serviceAccountName: tap-default
  source:
    git:
      url: https://github.com/bmoussaud/my-birds-svc
      ref:
        branch: main
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: postgres
  serviceClaims:   
    - name: birds-database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: aso-psql-bindable
  params:
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: bmoussaud
    - name: gitops_repository_name
      value: micropets-app-gitops
    - name: xxxx_gitops_repository
      value: https://github.com/bmoussaud/micropets-app-gitops
    - name: port
      value: 8080
    - name: observability
      value: false
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
