apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: birds
  labels:    
    apps.tanzu.vmware.com/workload-type: web        
    app.kubernetes.io/name: birds
    app.kubernetes.io/part-of: micropets-app
    micropets/kind: backend
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  serviceAccountName: tap-default
  source:
    git:
      url: https://github.com/bmoussaud/my-birds-svc
      ref:
        branch: master
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: postgres
  serviceClaims:
  - name: birds-database
    ref:
      apiVersion: sql.tanzu.vmware.com/v1
      kind: Postgres
      name: birds-database
  params:
    - name: port
      value: 8080
    - name: observability
      value: false
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
